version: '3.9' # Specify the version of the Docker Compose file format

services:
  db:
    image: postgres:15 # Use the official Postgres 15 image
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist database data between container restarts
    environment:
      POSTGRES_USER: ${POSTGRES_USER} # Set the database user from .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Set the database password from .env
      POSTGRES_DB: ${POSTGRES_DB} # Set the database name from .env
    # ports:
    #   - "5432:5432" # (Optional) Expose Postgres port to host
    restart: always # Always restart the container unless stopped manually
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"] # Check if Postgres is ready
      interval: 10s # Run healthcheck every 10 seconds
      retries: 5 # Retry up to 5 times before marking as unhealthy

  pgadmin:
    image: dpage/pgadmin4 # Use the official pgAdmin 4 image
    restart: always # Always restart the container unless stopped manually
    ports:
      - "5050:80" # Map port 5050 on host to port 80 in container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL} # Set pgAdmin login email from .env
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD} # Set pgAdmin password from .env
    depends_on:
      - db # Wait for the db service to be ready before starting
    volumes:
      - pgadmin_data:/var/lib/pgadmin # Persist pgAdmin data

  web:
    build: . # Build the image from the Dockerfile in the current directory
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'" # Remove old server PID and start Rails server
    volumes:
      - .:/app # Mount the current directory to /app in the container (for live code reload in development)
      - ./vendor/bundle:/usr/local/bundle # Persist installed gems between builds
    ports:
      - "3000:3000" # Map port 3000 on host to port 3000 in container
    depends_on:
      - db # Wait for the db service to be ready before starting
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB} # Set the database connection string
    restart: always # Always restart the container unless stopped manually

volumes:
  pgadmin_data: # Named volume for pgAdmin data
  postgres_data: # Named volume for Postgres data
